artifacts_root: artifacts

data_ingestion:
  source_url: https://github.com/rajarajeshwarir2021/Dataset-collections/raw/main/water_potability_dataset.zip
  root_dir: artifacts/data_ingestion
  unzip_dir: artifacts/data_ingestion
  zip_data_path: artifacts/data_ingestion/water_potability_dataset.zip

data_cleaning:
  root_dir: artifacts/data_cleaning
  unclean_data_path: artifacts/data_ingestion/water_potability_dataset.csv
  clean_data_path: artifacts/data_cleaning/water_potability_dataset.csv

data_validation:
  root_dir: artifacts/data_validation
  data_path: artifacts/data_cleaning/water_potability_dataset.csv
  status_file: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_cleaning/water_potability_dataset.csv
  status_file: artifacts/data_validation/status.txt
  feature_scaler_file_name: feature_scaler.joblib

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train_set.csv
  model_file_name: model.joblib

model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test_set.csv
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: metrics.json

model_prediction:
  model_path: artifacts/model_trainer/model.joblib

web_app:
  static_dir: web_app/static
  template_dir: web_app/template
  dataset_schema: artifacts/data_cleaning/dataset_schema.json
  feature_scaler: artifacts/data_transformation/feature_scaler.joblib
  model_path: artifacts/model_trainer/model.joblib
