artifacts_root: artifacts

data_ingestion:
  source_url: https://github.com/rajarajeshwarir2021/Dataset-collections/raw/main/water_potability_dataset.zip
  root_dir: artifacts/data_ingestion
  unzip_dir: artifacts/data_ingestion
  zip_data_path: artifacts/data_ingestion/water_potability_dataset.zip

data_validation:
  root_dir: artifacts/data_validation
  data_path: artifacts/data_ingestion/water_potability_dataset.csv
  status_file: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/data_ingestion/water_potability_dataset.csv
  status_file: artifacts/data_validation/status.txt
